import type { Metadata, Viewport } from "next";
import Script from "next/script";
import SeasonalBanner from "../components/SeasonalBanner";
import { AnalyticsListener } from "../components/Analytics";
import Assistant from "../components/Assistant";
import { ASSISTANT_ENABLED } from "../lib/assistant";
import "./globals.css";

// TODO: once the new domain is chosen, set NEXT_PUBLIC_SITE_URL in .env.local
// and swap the fallback below. Using the current live legacy domain as a
// placeholder for now since it's the only real domain this business owns.
const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL || "https://www.zacsbinandpressurecleaning.com.au";

// Set NEXT_PUBLIC_GA_ID in .env.local once you have a real GA4 measurement
// ID (looks like G-XXXXXXXXXX). Nothing loads or tracks until it's set —
// no placeholder ID is baked in here.
const gaId = process.env.NEXT_PUBLIC_GA_ID;

// The Google Ads conversion tag for this account (looks like AW-XXXXXXXXXX,
// found in Google Ads > Tools > Conversions > Google tag). Kept as its own
// env var and its own script block, deliberately separate from the GA4 tag
// above, so this can be installed, rotated or removed without ever touching
// the GA4 tag's settings. Nothing loads until NEXT_PUBLIC_ADS_ID is set.
const adsId = process.env.NEXT_PUBLIC_ADS_ID;

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "Cairns Exterior Cleaning | Cairns Bin Cleaning",
    template: "%s",
  },
  description:
    "Pressure cleaning, bin cleaning, roof cleaning, solar panel cleaning and exterior maintenance across Cairns and FNQ.",
  openGraph: {
    siteName: "Cairns Bin Cleaning",
    locale: "en_AU",
    type: "website",
    images: [{ url: "/media/IMG_3027.jpg" }],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/media/IMG_3027.jpg"],
  },
  verification: {
    google: "qy0_aHd1bFTi5PQaDgJGn-PNBpn3Uxu4fs8nlzOqJOM",
  },
  // Generated by app/manifest.ts — this is what makes the site installable
  // to a phone home screen. See that file for why there's no service worker.
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    title: "CBC Quote",
    // The quote tool runs its own dark map edge-to-edge, so the iOS status
    // bar sits over the page rather than above it.
    statusBarStyle: "black-translucent",
  },
  icons: {
    icon: [
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  // viewportFit matters once installed: the tool paints to the screen edges
  // and uses env(safe-area-inset-*) to keep controls clear of the notch and
  // the home indicator.
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#0A4D3A" },
    { media: "(prefers-color-scheme: dark)", color: "#06110E" },
  ],
};

const localBusinessJsonLd = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  name: "Cairns Bin Cleaning",
  telephone: "+61434052755",
  url: siteUrl,
  // Character-for-character match with the "Service area" list on the real
  // Google Business Profile listing (checked 2026-09-17, Location tab).
  // Keep this list and the one in app/[slug]/page.tsx in sync with GBP —
  // don't hand-edit one without the other.
  areaServed: [
    "Cairns QLD, Australia",
    "Cairns City QLD, Australia",
    "Bentley Park QLD, Australia",
    "Manoora QLD 4870, Australia",
    "Manunda QLD 4870, Australia",
    "Yorkeys Knob QLD, Australia",
    "Kanimbla QLD 4870, Australia",
    "Machans Beach QLD, Australia",
    "Redlynch QLD 4870, Australia",
    "Trinity Beach QLD, Australia",
    "Brinsmead QLD 4870, Australia",
    "Edge Hill QLD 4870, Australia",
    "Stratford QLD 4870, Australia",
    "Westcourt QLD 4870, Australia",
    "Whitfield QLD 4870, Australia",
    "Freshwater QLD 4870, Australia",
    "Gordonvale QLD 4865, Australia",
    "Mooroobool QLD 4870, Australia",
    "Smithfield QLD 4878, Australia",
    "Parramatta Park QLD 4870, Australia",
  ],
  taxID: "36 318 413 406",
  description:
    "Bin cleaning, pressure cleaning, roof cleaning, window cleaning, solar panel cleaning and exterior maintenance across Cairns and Far North Queensland.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en-AU" data-scroll-behavior="smooth">
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(localBusinessJsonLd).replace(/</g, "\\u003c"),
          }}
        />
        <AnalyticsListener />
        <SeasonalBanner />
        {children}
        {/* Website assistant: shows only once ANTHROPIC_API_KEY is set. */}
        {ASSISTANT_ENABLED() && <Assistant />}
        {/* One gtag.js for both GA4 and Google Ads: the second copy was
            ~150 KB of duplicate script on every page. */}
        {(gaId || adsId) && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${gaId || adsId}`}
              /* Loads when the page is idle so it never competes with the
                 first paint on a phone. Events before then wait in
                 dataLayer and are sent when it arrives. */
              strategy="lazyOnload"
            />
            <Script id="gtag-init" strategy="afterInteractive">
              {`window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                ${gaId ? `gtag('config', '${gaId}');` : ""}
                ${adsId ? `gtag('config', '${adsId}');` : ""}`}
            </Script>
          </>
        )}
      </body>
    </html>
  );
}
