/* Suburb landing pages (/service-areas/[suburb]).

   Every suburb we actually cover gets a page, and every page has to earn it
   with real, page-specific facts — otherwise it's a doorway page, which
   Google treats as spam:

   - its own postcode and its own distance from base, both computed from the
     national address file (lib/suburbGeo.ts, generated by tools/suburb-geo.py);
   - the real jobs photographed in that suburb, if there are any;
   - otherwise the nearest real jobs we have, each labelled with the suburb it
     was actually taken in and how far that is from this one — never passed
     off as local work;
   - its own neighbour list, ordered by real distance.

   Everything else comes from the same sources as the rest of the site:
   calloutZones (lib/pricing.ts) and services (lib/services.ts). */

import { calloutZones } from "./pricing";
import { services, type Service, type ServicePhoto } from "./services";
import { SUBURB_GEO, kmBetween, type SuburbGeo } from "./suburbGeo";

export type SuburbJob = { photo: ServicePhoto; service: Service };
export type NearbyJob = SuburbJob & { km: number | null };

export type SuburbPage = {
  slug: string;
  name: string;
  zone: string;
  loading: number;
  geo: SuburbGeo;
  neighbours: string[]; // other suburbs in the same zone, nearest first
  jobs: SuburbJob[]; // photographed in this suburb
  nearby: NearbyJob[]; // nearest real jobs elsewhere, labelled with their own suburb
};

export function suburbSlug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const geoOf = (name: string): SuburbGeo =>
  SUBURB_GEO[name] ?? { lat: null, lon: null, postcode: null, kmFromBase: null, addresses: 0 };

function allJobs(): SuburbJob[] {
  const jobs: SuburbJob[] = [];
  for (const service of services) {
    for (const photo of service.gallery) {
      if (photo.suburb) jobs.push({ photo, service });
    }
  }
  return jobs;
}

const JOBS = allJobs();

function nearestJobs(name: string, zoneSuburbs: string[], limit = 3): NearbyJob[] {
  const here = geoOf(name);
  /* A locality with no addresses in the file (Ellis Beach) has no centre
     point, so fall back to jobs in the same zone, distance unknown. */
  if (here.lat == null)
    return JOBS.filter((j) => j.photo.suburb && zoneSuburbs.includes(j.photo.suburb))
      .map((j) => ({ ...j, km: null }))
      .filter((j, i, list) => list.findIndex((x) => x.photo.suburb === j.photo.suburb) === i)
      .slice(0, limit);
  return JOBS.filter((j) => j.photo.suburb !== name)
    .map((j) => ({ ...j, km: kmBetween(here, geoOf(j.photo.suburb ?? "")) }))
    .filter((j) => j.km != null)
    .sort((a, b) => (a.km as number) - (b.km as number))
    /* One photo per suburb, so the block shows three different places. */
    .filter((j, i, list) => list.findIndex((x) => x.photo.suburb === j.photo.suburb) === i)
    .slice(0, limit);
}

export const suburbPages: SuburbPage[] = calloutZones.flatMap((zone) =>
  zone.suburbs.map((name) => {
    const here = geoOf(name);
    const jobs = JOBS.filter((j) => j.photo.suburb === name);
    return {
      slug: suburbSlug(name),
      name,
      zone: zone.name,
      loading: zone.loading,
      geo: here,
      neighbours: zone.suburbs
        .filter((s) => s !== name)
        .sort((a, b) => (kmBetween(here, geoOf(a)) ?? 99) - (kmBetween(here, geoOf(b)) ?? 99)),
      jobs,
      nearby: jobs.length ? [] : nearestJobs(name, zone.suburbs),
    };
  })
);

export function getSuburbPage(slug: string) {
  return suburbPages.find((p) => p.slug === slug);
}
