/* GENERATED by tools/suburb-geo.py — do not edit by hand.

   Centre point = the median of every real address in that suburb in
   data/cairns-addresses.txt (the same national address file the address
   search uses). Postcode = the one most of those addresses carry.
   kmFromBase = straight-line distance from Mount Sheridan, where the truck starts.
   Suburbs with no addresses in the file (tiny localities) have nulls and the
   pages simply leave those details out. */

export type SuburbGeo = { lat: number | null; lon: number | null; postcode: string | null; kmFromBase: number | null; addresses: number };

export const SUBURB_GEO: Record<string, SuburbGeo> = {
  "Cairns City": { lat: -16.92099, lon: 145.7752, postcode: "4870", kmFromBase: 8.6, addresses: 5685 },
  "Cairns North": { lat: -16.90903, lon: 145.76166, postcode: "4870", kmFromBase: 9.3, addresses: 4620 },
  "Bungalow": { lat: -16.93567, lon: 145.76008, postcode: "4870", kmFromBase: 6.5, addresses: 2612 },
  "Portsmith": { lat: -16.93948, lon: 145.76761, postcode: "4870", kmFromBase: 6.4, addresses: 1007 },
  "Westcourt": { lat: -16.92966, lon: 145.75463, postcode: "4870", kmFromBase: 6.9, addresses: 2859 },
  "Parramatta Park": { lat: -16.92097, lon: 145.76381, postcode: "4870", kmFromBase: 8.1, addresses: 2425 },
  "Earlville": { lat: -16.94463, lon: 145.73704, postcode: "4870", kmFromBase: 4.9, addresses: 2638 },
  "Manoora": { lat: -16.91538, lon: 145.7375, postcode: "4870", kmFromBase: 8.2, addresses: 3655 },
  "Manunda": { lat: -16.92048, lon: 145.74707, postcode: "4870", kmFromBase: 7.7, addresses: 3747 },
  "Aeroglen": { lat: -16.88316, lon: 145.74672, postcode: "4870", kmFromBase: 11.8, addresses: 460 },
  "Freshwater": { lat: -16.88197, lon: 145.71456, postcode: "4870", kmFromBase: 12.1, addresses: 1232 },
  "Stratford": { lat: -16.87668, lon: 145.73071, postcode: "4870", kmFromBase: 12.5, addresses: 713 },
  "Edge Hill": { lat: -16.90153, lon: 145.74109, postcode: "4870", kmFromBase: 9.7, addresses: 2332 },
  "Whitfield": { lat: -16.90512, lon: 145.72969, postcode: "4870", kmFromBase: 9.3, addresses: 2279 },
  "Brinsmead": { lat: -16.90132, lon: 145.71532, postcode: "4870", kmFromBase: 10.0, addresses: 2219 },
  "Machans Beach": { lat: -16.85316, lon: 145.7472, postcode: "4878", kmFromBase: 15.1, addresses: 566 },
  "Holloways Beach": { lat: -16.84091, lon: 145.73826, postcode: "4878", kmFromBase: 16.5, addresses: 1506 },
  "Yorkeys Knob": { lat: -16.80943, lon: 145.72176, postcode: "4878", kmFromBase: 20.0, addresses: 2004 },
  "Caravonica": { lat: -16.86375, lon: 145.68634, postcode: "4878", kmFromBase: 14.9, addresses: 1190 },
  "Kamerunga": { lat: -16.87562, lon: 145.68629, postcode: "4870", kmFromBase: 13.7, addresses: 495 },
  "Smithfield": { lat: -16.82479, lon: 145.69391, postcode: "4878", kmFromBase: 18.8, addresses: 4020 },
  "Trinity Park": { lat: -16.80838, lon: 145.70233, postcode: "4879", kmFromBase: 20.4, addresses: 1628 },
  "Trinity Beach": { lat: -16.79025, lon: 145.69523, postcode: "4879", kmFromBase: 22.5, addresses: 4750 },
  "Kewarra Beach": { lat: -16.78793, lon: 145.67908, postcode: "4879", kmFromBase: 23.2, addresses: 3105 },
  "Clifton Beach": { lat: -16.76894, lon: 145.67451, postcode: "4879", kmFromBase: 25.3, addresses: 2238 },
  "Palm Cove": { lat: -16.74723, lon: 145.66821, postcode: "4879", kmFromBase: 27.8, addresses: 3101 },
  "Ellis Beach": { lat: null, lon: null, postcode: null, kmFromBase: null, addresses: 0 },
  "Redlynch": { lat: -16.90264, lon: 145.69458, postcode: "4870", kmFromBase: 10.6, addresses: 4662 },
  "Bayview Heights": { lat: -16.96031, lon: 145.72973, postcode: "4868", kmFromBase: 3.3, addresses: 1761 },
  "Mooroobool": { lat: -16.93407, lon: 145.73422, postcode: "4870", kmFromBase: 6.1, addresses: 3407 },
  "Kanimbla": { lat: -16.92311, lon: 145.72282, postcode: "4870", kmFromBase: 7.5, addresses: 1221 },
  "Woree": { lat: -16.95778, lon: 145.74341, postcode: "4868", kmFromBase: 3.6, addresses: 3249 },
  "White Rock": { lat: -16.97658, lon: 145.74895, postcode: "4868", kmFromBase: 1.9, addresses: 2439 },
  "Mount Sheridan": { lat: -16.98897, lon: 145.73611, postcode: "4868", kmFromBase: 0.0, addresses: 3761 },
  "Bentley Park": { lat: -17.00831, lon: 145.72314, postcode: "4869", kmFromBase: 2.6, addresses: 3814 },
  "Edmonton": { lat: -17.02367, lon: 145.73722, postcode: "4869", kmFromBase: 3.9, addresses: 5508 },
  "Gordonvale": { lat: -17.09124, lon: 145.77307, postcode: "4865", kmFromBase: 12.0, addresses: 3623 },
};

export function kmBetween(a: { lat: number | null; lon: number | null }, b: { lat: number | null; lon: number | null }) {
  if (a.lat == null || a.lon == null || b.lat == null || b.lon == null) return null;
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLon = ((b.lon - a.lon) * Math.PI) / 180;
  const x =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((a.lat * Math.PI) / 180) * Math.cos((b.lat * Math.PI) / 180) * Math.sin(dLon / 2) ** 2;
  return Math.round(2 * R * Math.asin(Math.sqrt(x)) * 10) / 10;
}
