"""Suburb centres and distances, computed from the real address file.

Reads data/cairns-addresses.txt (the G-NAF extract the address search uses)
and writes lib/suburbGeo.ts: one centre point and postcode per suburb, plus
the distance from base. Re-run it after tools/refresh-addresses.py:

    python3 tools/suburb-geo.py

Nothing here is estimated by hand — the centre is the median of every real
address point in that suburb, so it moves only when the address file does.
"""
import re, statistics, math, json, pathlib

SUBURBS = ["Cairns City","Cairns North","Bungalow","Portsmith","Westcourt","Parramatta Park",
"Earlville","Manoora","Manunda","Aeroglen","Freshwater","Stratford","Edge Hill","Whitfield",
"Brinsmead","Machans Beach","Holloways Beach","Yorkeys Knob","Caravonica","Kamerunga","Smithfield",
"Trinity Park","Trinity Beach","Kewarra Beach","Clifton Beach","Palm Cove","Ellis Beach","Redlynch",
"Bayview Heights","Mooroobool","Kanimbla","Woree","White Rock","Mount Sheridan","Bentley Park",
"Edmonton","Gordonvale"]

BASE = "Mount Sheridan"  # where the truck starts from

pts = {s: [] for s in SUBURBS}
pcs = {s: {} for s in SUBURBS}
root = pathlib.Path(__file__).resolve().parents[1]
for line in (root / "data/cairns-addresses.txt").open(encoding="utf8", errors="ignore"):
    parts = line.rstrip("\n").split("|")
    if len(parts) < 3:
        continue
    label, lat, lon = parts[0], parts[1], parts[2]
    m = re.search(r",\s*([A-Za-z' ]+?)\s+(\d{4})\s*$", label)
    if not m:
        continue
    name, pc = m.group(1).strip(), m.group(2)
    if name not in pts:
        continue
    try:
        pts[name].append((float(lat), float(lon)))
    except ValueError:
        continue
    pcs[name][pc] = pcs[name].get(pc, 0) + 1

def km(a, b):
    R = 6371.0
    dlat = math.radians(b[0] - a[0]); dlon = math.radians(b[1] - a[1])
    x = math.sin(dlat/2)**2 + math.cos(math.radians(a[0]))*math.cos(math.radians(b[0]))*math.sin(dlon/2)**2
    return 2 * R * math.asin(math.sqrt(x))

centres = {}
for s in SUBURBS:
    if not pts[s]:
        continue
    centres[s] = (round(statistics.median(p[0] for p in pts[s]), 5),
                  round(statistics.median(p[1] for p in pts[s]), 5))

base = centres[BASE]
rows = []
for s in SUBURBS:
    if s not in centres:
        rows.append(f'  "{s}": {{ lat: null, lon: null, postcode: null, kmFromBase: null, addresses: 0 }},')
        continue
    pc = max(pcs[s].items(), key=lambda kv: kv[1])[0]
    rows.append(f'  "{s}": {{ lat: {centres[s][0]}, lon: {centres[s][1]}, postcode: "{pc}", '
                f'kmFromBase: {round(km(base, centres[s]), 1)}, addresses: {len(pts[s])} }},')

out = f'''/* GENERATED by tools/suburb-geo.py — do not edit by hand.

   Centre point = the median of every real address in that suburb in
   data/cairns-addresses.txt (the same national address file the address
   search uses). Postcode = the one most of those addresses carry.
   kmFromBase = straight-line distance from {BASE}, where the truck starts.
   Suburbs with no addresses in the file (tiny localities) have nulls and the
   pages simply leave those details out. */

export type SuburbGeo = {{ lat: number | null; lon: number | null; postcode: string | null; kmFromBase: number | null; addresses: number }};

export const SUBURB_GEO: Record<string, SuburbGeo> = {{
{chr(10).join(rows)}
}};

export function kmBetween(a: {{ lat: number | null; lon: number | null }}, b: {{ lat: number | null; lon: number | null }}) {{
  if (a.lat == null || a.lon == null || b.lat == null || b.lon == null) return null;
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLon = ((b.lon - a.lon) * Math.PI) / 180;
  const x =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((a.lat * Math.PI) / 180) * Math.cos((b.lat * Math.PI) / 180) * Math.sin(dLon / 2) ** 2;
  return Math.round(2 * R * Math.asin(Math.sqrt(x)) * 10) / 10;
}}
'''
(root / "lib/suburbGeo.ts").write_text(out)
print("wrote lib/suburbGeo.ts", len(centres), "suburbs with data")
